- hosts: "{{ env }}"
  become: yes
  tasks: 
    - name: remove any previous app services
      shell: | 
         if [ `kubectl get deploy | grep -v NAME | awk '{print $1}' | grep myapp-train-schedule | wc -l` -gt 0 ]; then  
            kubectl delete deploy `kubectl get deploy | grep -v NAME | awk '{print $1}' | grep myapp-train-schedule`
         else 
            echo "No app deployments found"
         fi
         if [ `kubectl get svc | grep myapp-train-schedule-svc  | awk '{print $1}' | wc -l` -gt 0 ]; then
            kubectl delete svc `kubectl get svc | grep myapp-train-schedule-svc | awk '{print $1}'`
         else
            echo "No app service found"
         fi
    - name: deploy app
      shell: kubectl create deploy myapp-train-schedule --image=vidyadhards/cicd-pipeline-train-schedule-autodeploy:{{ build }}
    - name: increase replicas 
      shell: kubectl scale deploy myapp-train-schedule --replicas=2
    - name: deploy service
      shell: kubectl expose deploy myapp-train-schedule --name myapp-train-schedule-svc --port=8080 --target-port=8080
